
#if (!defined NEKO_PP_FOR_EACH || !defined NEKO_PP_PARAMS)

// 横向迭代, NEKO_PP_PARAMS(x, 3) => x1, x2, x3

#define NEKO_PP_PARAMS_0(x)
#define NEKO_PP_PARAMS_1(x) x##1
#define NEKO_PP_PARAMS_2(x) NEKO_PP_PARAMS_1(x), x##2
#define NEKO_PP_PARAMS_3(x) NEKO_PP_PARAMS_2(x), x##3
#define NEKO_PP_PARAMS_4(x) NEKO_PP_PARAMS_3(x), x##4
#define NEKO_PP_PARAMS_5(x) NEKO_PP_PARAMS_4(x), x##5
#define NEKO_PP_PARAMS_6(x) NEKO_PP_PARAMS_5(x), x##6
#define NEKO_PP_PARAMS_7(x) NEKO_PP_PARAMS_6(x), x##7
#define NEKO_PP_PARAMS_8(x) NEKO_PP_PARAMS_7(x), x##8
#define NEKO_PP_PARAMS_9(x) NEKO_PP_PARAMS_8(x), x##9
#define NEKO_PP_PARAMS_10(x) NEKO_PP_PARAMS_9(x), x##10
#define NEKO_PP_PARAMS_11(x) NEKO_PP_PARAMS_10(x), x##11
#define NEKO_PP_PARAMS_12(x) NEKO_PP_PARAMS_11(x), x##12
#define NEKO_PP_PARAMS_13(x) NEKO_PP_PARAMS_12(x), x##13
#define NEKO_PP_PARAMS_14(x) NEKO_PP_PARAMS_13(x), x##14
#define NEKO_PP_PARAMS_15(x) NEKO_PP_PARAMS_14(x), x##15
#define NEKO_PP_PARAMS_16(x) NEKO_PP_PARAMS_15(x), x##16
#define NEKO_PP_PARAMS_17(x) NEKO_PP_PARAMS_16(x), x##17
#define NEKO_PP_PARAMS_18(x) NEKO_PP_PARAMS_17(x), x##18
#define NEKO_PP_PARAMS_19(x) NEKO_PP_PARAMS_18(x), x##19
#define NEKO_PP_PARAMS_20(x) NEKO_PP_PARAMS_19(x), x##20
#define NEKO_PP_PARAMS_21(x) NEKO_PP_PARAMS_20(x), x##21
#define NEKO_PP_PARAMS_22(x) NEKO_PP_PARAMS_21(x), x##22
#define NEKO_PP_PARAMS_23(x) NEKO_PP_PARAMS_22(x), x##23
#define NEKO_PP_PARAMS_24(x) NEKO_PP_PARAMS_23(x), x##24
#define NEKO_PP_PARAMS_25(x) NEKO_PP_PARAMS_24(x), x##25
#define NEKO_PP_PARAMS_26(x) NEKO_PP_PARAMS_25(x), x##26
#define NEKO_PP_PARAMS_27(x) NEKO_PP_PARAMS_26(x), x##27
#define NEKO_PP_PARAMS_28(x) NEKO_PP_PARAMS_27(x), x##28
#define NEKO_PP_PARAMS_29(x) NEKO_PP_PARAMS_28(x), x##29
#define NEKO_PP_PARAMS_30(x) NEKO_PP_PARAMS_29(x), x##30
#define NEKO_PP_PARAMS_31(x) NEKO_PP_PARAMS_30(x), x##31
#define NEKO_PP_PARAMS_32(x) NEKO_PP_PARAMS_31(x), x##32
#define NEKO_PP_PARAMS_33(x) NEKO_PP_PARAMS_32(x), x##33
#define NEKO_PP_PARAMS_34(x) NEKO_PP_PARAMS_33(x), x##34
#define NEKO_PP_PARAMS_35(x) NEKO_PP_PARAMS_34(x), x##35
#define NEKO_PP_PARAMS_36(x) NEKO_PP_PARAMS_35(x), x##36
#define NEKO_PP_PARAMS_37(x) NEKO_PP_PARAMS_36(x), x##37
#define NEKO_PP_PARAMS_38(x) NEKO_PP_PARAMS_37(x), x##38
#define NEKO_PP_PARAMS_39(x) NEKO_PP_PARAMS_38(x), x##39
#define NEKO_PP_PARAMS_40(x) NEKO_PP_PARAMS_39(x), x##40
#define NEKO_PP_PARAMS_41(x) NEKO_PP_PARAMS_40(x), x##41
#define NEKO_PP_PARAMS_42(x) NEKO_PP_PARAMS_41(x), x##42
#define NEKO_PP_PARAMS_43(x) NEKO_PP_PARAMS_42(x), x##43
#define NEKO_PP_PARAMS_44(x) NEKO_PP_PARAMS_43(x), x##44
#define NEKO_PP_PARAMS_45(x) NEKO_PP_PARAMS_44(x), x##45
#define NEKO_PP_PARAMS_46(x) NEKO_PP_PARAMS_45(x), x##46
#define NEKO_PP_PARAMS_47(x) NEKO_PP_PARAMS_46(x), x##47
#define NEKO_PP_PARAMS_48(x) NEKO_PP_PARAMS_47(x), x##48
#define NEKO_PP_PARAMS_49(x) NEKO_PP_PARAMS_48(x), x##49
#define NEKO_PP_PARAMS_50(x) NEKO_PP_PARAMS_49(x), x##50
#define NEKO_PP_PARAMS_51(x) NEKO_PP_PARAMS_50(x), x##51
#define NEKO_PP_PARAMS_52(x) NEKO_PP_PARAMS_51(x), x##52
#define NEKO_PP_PARAMS_53(x) NEKO_PP_PARAMS_52(x), x##53
#define NEKO_PP_PARAMS_54(x) NEKO_PP_PARAMS_53(x), x##54
#define NEKO_PP_PARAMS_55(x) NEKO_PP_PARAMS_54(x), x##55
#define NEKO_PP_PARAMS_56(x) NEKO_PP_PARAMS_55(x), x##56
#define NEKO_PP_PARAMS_57(x) NEKO_PP_PARAMS_56(x), x##57
#define NEKO_PP_PARAMS_58(x) NEKO_PP_PARAMS_57(x), x##58
#define NEKO_PP_PARAMS_59(x) NEKO_PP_PARAMS_58(x), x##59
#define NEKO_PP_PARAMS_60(x) NEKO_PP_PARAMS_59(x), x##60
#define NEKO_PP_PARAMS_61(x) NEKO_PP_PARAMS_60(x), x##61
#define NEKO_PP_PARAMS_62(x) NEKO_PP_PARAMS_61(x), x##62
#define NEKO_PP_PARAMS_63(x) NEKO_PP_PARAMS_62(x), x##63

#define NEKO_PP_PARAMS(x, N) NEKO_PP_PARAMS_##N(x)

// 横向迭代, NEKO_PP_CALL_PARAMS(f, x, 3) => f(x1), f(x2), f(x3)

#define NEKO_PP_CALL_PARAMS_0(f, x)
#define NEKO_PP_CALL_PARAMS_1(f, x) f(x##1)
#define NEKO_PP_CALL_PARAMS_2(f, x) NEKO_PP_CALL_PARAMS_1(f, x), f(x##2)
#define NEKO_PP_CALL_PARAMS_3(f, x) NEKO_PP_CALL_PARAMS_2(f, x), f(x##3)
#define NEKO_PP_CALL_PARAMS_4(f, x) NEKO_PP_CALL_PARAMS_3(f, x), f(x##4)
#define NEKO_PP_CALL_PARAMS_5(f, x) NEKO_PP_CALL_PARAMS_4(f, x), f(x##5)
#define NEKO_PP_CALL_PARAMS_6(f, x) NEKO_PP_CALL_PARAMS_5(f, x), f(x##6)
#define NEKO_PP_CALL_PARAMS_7(f, x) NEKO_PP_CALL_PARAMS_6(f, x), f(x##7)
#define NEKO_PP_CALL_PARAMS_8(f, x) NEKO_PP_CALL_PARAMS_7(f, x), f(x##8)
#define NEKO_PP_CALL_PARAMS_9(f, x) NEKO_PP_CALL_PARAMS_8(f, x), f(x##9)
#define NEKO_PP_CALL_PARAMS_10(f, x) NEKO_PP_CALL_PARAMS_9(f, x), f(x##10)
#define NEKO_PP_CALL_PARAMS_11(f, x) NEKO_PP_CALL_PARAMS_10(f, x), f(x##11)
#define NEKO_PP_CALL_PARAMS_12(f, x) NEKO_PP_CALL_PARAMS_11(f, x), f(x##12)
#define NEKO_PP_CALL_PARAMS_13(f, x) NEKO_PP_CALL_PARAMS_12(f, x), f(x##13)
#define NEKO_PP_CALL_PARAMS_14(f, x) NEKO_PP_CALL_PARAMS_13(f, x), f(x##14)
#define NEKO_PP_CALL_PARAMS_15(f, x) NEKO_PP_CALL_PARAMS_14(f, x), f(x##15)
#define NEKO_PP_CALL_PARAMS_16(f, x) NEKO_PP_CALL_PARAMS_15(f, x), f(x##16)
#define NEKO_PP_CALL_PARAMS_17(f, x) NEKO_PP_CALL_PARAMS_16(f, x), f(x##17)
#define NEKO_PP_CALL_PARAMS_18(f, x) NEKO_PP_CALL_PARAMS_17(f, x), f(x##18)
#define NEKO_PP_CALL_PARAMS_19(f, x) NEKO_PP_CALL_PARAMS_18(f, x), f(x##19)
#define NEKO_PP_CALL_PARAMS_20(f, x) NEKO_PP_CALL_PARAMS_19(f, x), f(x##20)
#define NEKO_PP_CALL_PARAMS_21(f, x) NEKO_PP_CALL_PARAMS_20(f, x), f(x##21)
#define NEKO_PP_CALL_PARAMS_22(f, x) NEKO_PP_CALL_PARAMS_21(f, x), f(x##22)
#define NEKO_PP_CALL_PARAMS_23(f, x) NEKO_PP_CALL_PARAMS_22(f, x), f(x##23)
#define NEKO_PP_CALL_PARAMS_24(f, x) NEKO_PP_CALL_PARAMS_23(f, x), f(x##24)
#define NEKO_PP_CALL_PARAMS_25(f, x) NEKO_PP_CALL_PARAMS_24(f, x), f(x##25)
#define NEKO_PP_CALL_PARAMS_26(f, x) NEKO_PP_CALL_PARAMS_25(f, x), f(x##26)
#define NEKO_PP_CALL_PARAMS_27(f, x) NEKO_PP_CALL_PARAMS_26(f, x), f(x##27)
#define NEKO_PP_CALL_PARAMS_28(f, x) NEKO_PP_CALL_PARAMS_27(f, x), f(x##28)
#define NEKO_PP_CALL_PARAMS_29(f, x) NEKO_PP_CALL_PARAMS_28(f, x), f(x##29)
#define NEKO_PP_CALL_PARAMS_30(f, x) NEKO_PP_CALL_PARAMS_29(f, x), f(x##30)
#define NEKO_PP_CALL_PARAMS_31(f, x) NEKO_PP_CALL_PARAMS_30(f, x), f(x##31)
#define NEKO_PP_CALL_PARAMS_32(f, x) NEKO_PP_CALL_PARAMS_31(f, x), f(x##32)
#define NEKO_PP_CALL_PARAMS_33(f, x) NEKO_PP_CALL_PARAMS_32(f, x), f(x##33)
#define NEKO_PP_CALL_PARAMS_34(f, x) NEKO_PP_CALL_PARAMS_33(f, x), f(x##34)
#define NEKO_PP_CALL_PARAMS_35(f, x) NEKO_PP_CALL_PARAMS_34(f, x), f(x##35)
#define NEKO_PP_CALL_PARAMS_36(f, x) NEKO_PP_CALL_PARAMS_35(f, x), f(x##36)
#define NEKO_PP_CALL_PARAMS_37(f, x) NEKO_PP_CALL_PARAMS_36(f, x), f(x##37)
#define NEKO_PP_CALL_PARAMS_38(f, x) NEKO_PP_CALL_PARAMS_37(f, x), f(x##38)
#define NEKO_PP_CALL_PARAMS_39(f, x) NEKO_PP_CALL_PARAMS_38(f, x), f(x##39)
#define NEKO_PP_CALL_PARAMS_40(f, x) NEKO_PP_CALL_PARAMS_39(f, x), f(x##40)
#define NEKO_PP_CALL_PARAMS_41(f, x) NEKO_PP_CALL_PARAMS_40(f, x), f(x##41)
#define NEKO_PP_CALL_PARAMS_42(f, x) NEKO_PP_CALL_PARAMS_41(f, x), f(x##42)
#define NEKO_PP_CALL_PARAMS_43(f, x) NEKO_PP_CALL_PARAMS_42(f, x), f(x##43)
#define NEKO_PP_CALL_PARAMS_44(f, x) NEKO_PP_CALL_PARAMS_43(f, x), f(x##44)
#define NEKO_PP_CALL_PARAMS_45(f, x) NEKO_PP_CALL_PARAMS_44(f, x), f(x##45)
#define NEKO_PP_CALL_PARAMS_46(f, x) NEKO_PP_CALL_PARAMS_45(f, x), f(x##46)
#define NEKO_PP_CALL_PARAMS_47(f, x) NEKO_PP_CALL_PARAMS_46(f, x), f(x##47)
#define NEKO_PP_CALL_PARAMS_48(f, x) NEKO_PP_CALL_PARAMS_47(f, x), f(x##48)
#define NEKO_PP_CALL_PARAMS_49(f, x) NEKO_PP_CALL_PARAMS_48(f, x), f(x##49)
#define NEKO_PP_CALL_PARAMS_50(f, x) NEKO_PP_CALL_PARAMS_49(f, x), f(x##50)
#define NEKO_PP_CALL_PARAMS_51(f, x) NEKO_PP_CALL_PARAMS_50(f, x), f(x##51)
#define NEKO_PP_CALL_PARAMS_52(f, x) NEKO_PP_CALL_PARAMS_51(f, x), f(x##52)
#define NEKO_PP_CALL_PARAMS_53(f, x) NEKO_PP_CALL_PARAMS_52(f, x), f(x##53)
#define NEKO_PP_CALL_PARAMS_54(f, x) NEKO_PP_CALL_PARAMS_53(f, x), f(x##54)
#define NEKO_PP_CALL_PARAMS_55(f, x) NEKO_PP_CALL_PARAMS_54(f, x), f(x##55)
#define NEKO_PP_CALL_PARAMS_56(f, x) NEKO_PP_CALL_PARAMS_55(f, x), f(x##56)
#define NEKO_PP_CALL_PARAMS_57(f, x) NEKO_PP_CALL_PARAMS_56(f, x), f(x##57)
#define NEKO_PP_CALL_PARAMS_58(f, x) NEKO_PP_CALL_PARAMS_57(f, x), f(x##58)
#define NEKO_PP_CALL_PARAMS_59(f, x) NEKO_PP_CALL_PARAMS_58(f, x), f(x##59)
#define NEKO_PP_CALL_PARAMS_60(f, x) NEKO_PP_CALL_PARAMS_59(f, x), f(x##60)
#define NEKO_PP_CALL_PARAMS_61(f, x) NEKO_PP_CALL_PARAMS_60(f, x), f(x##61)
#define NEKO_PP_CALL_PARAMS_62(f, x) NEKO_PP_CALL_PARAMS_61(f, x), f(x##62)
#define NEKO_PP_CALL_PARAMS_63(f, x) NEKO_PP_CALL_PARAMS_62(f, x), f(x##63)

#define NEKO_PP_CALL_PARAMS(f, x, N) NEKO_PP_CALL_PARAMS_##N(f, x)

// 纵向迭代

#define NEKO_PP_FOR_EACH_0(x)
#define NEKO_PP_FOR_EACH_1(x) NEKO_PP_FOR_EACH_0(x) x(1)
#define NEKO_PP_FOR_EACH_2(x) NEKO_PP_FOR_EACH_1(x) x(2)
#define NEKO_PP_FOR_EACH_3(x) NEKO_PP_FOR_EACH_2(x) x(3)
#define NEKO_PP_FOR_EACH_4(x) NEKO_PP_FOR_EACH_3(x) x(4)
#define NEKO_PP_FOR_EACH_5(x) NEKO_PP_FOR_EACH_4(x) x(5)
#define NEKO_PP_FOR_EACH_6(x) NEKO_PP_FOR_EACH_5(x) x(6)
#define NEKO_PP_FOR_EACH_7(x) NEKO_PP_FOR_EACH_6(x) x(7)
#define NEKO_PP_FOR_EACH_8(x) NEKO_PP_FOR_EACH_7(x) x(8)
#define NEKO_PP_FOR_EACH_9(x) NEKO_PP_FOR_EACH_8(x) x(9)
#define NEKO_PP_FOR_EACH_10(x) NEKO_PP_FOR_EACH_9(x) x(10)
#define NEKO_PP_FOR_EACH_11(x) NEKO_PP_FOR_EACH_10(x) x(11)
#define NEKO_PP_FOR_EACH_12(x) NEKO_PP_FOR_EACH_11(x) x(12)
#define NEKO_PP_FOR_EACH_13(x) NEKO_PP_FOR_EACH_12(x) x(13)
#define NEKO_PP_FOR_EACH_14(x) NEKO_PP_FOR_EACH_13(x) x(14)
#define NEKO_PP_FOR_EACH_15(x) NEKO_PP_FOR_EACH_14(x) x(15)
#define NEKO_PP_FOR_EACH_16(x) NEKO_PP_FOR_EACH_15(x) x(16)
#define NEKO_PP_FOR_EACH_17(x) NEKO_PP_FOR_EACH_16(x) x(17)
#define NEKO_PP_FOR_EACH_18(x) NEKO_PP_FOR_EACH_17(x) x(18)
#define NEKO_PP_FOR_EACH_19(x) NEKO_PP_FOR_EACH_18(x) x(19)
#define NEKO_PP_FOR_EACH_20(x) NEKO_PP_FOR_EACH_19(x) x(20)
#define NEKO_PP_FOR_EACH_21(x) NEKO_PP_FOR_EACH_20(x) x(21)
#define NEKO_PP_FOR_EACH_22(x) NEKO_PP_FOR_EACH_21(x) x(22)
#define NEKO_PP_FOR_EACH_23(x) NEKO_PP_FOR_EACH_22(x) x(23)
#define NEKO_PP_FOR_EACH_24(x) NEKO_PP_FOR_EACH_23(x) x(24)
#define NEKO_PP_FOR_EACH_25(x) NEKO_PP_FOR_EACH_24(x) x(25)
#define NEKO_PP_FOR_EACH_26(x) NEKO_PP_FOR_EACH_25(x) x(26)
#define NEKO_PP_FOR_EACH_27(x) NEKO_PP_FOR_EACH_26(x) x(27)
#define NEKO_PP_FOR_EACH_28(x) NEKO_PP_FOR_EACH_27(x) x(28)
#define NEKO_PP_FOR_EACH_29(x) NEKO_PP_FOR_EACH_28(x) x(29)
#define NEKO_PP_FOR_EACH_30(x) NEKO_PP_FOR_EACH_29(x) x(30)
#define NEKO_PP_FOR_EACH_31(x) NEKO_PP_FOR_EACH_30(x) x(31)
#define NEKO_PP_FOR_EACH_32(x) NEKO_PP_FOR_EACH_31(x) x(32)
#define NEKO_PP_FOR_EACH_33(x) NEKO_PP_FOR_EACH_32(x) x(33)
#define NEKO_PP_FOR_EACH_34(x) NEKO_PP_FOR_EACH_33(x) x(34)
#define NEKO_PP_FOR_EACH_35(x) NEKO_PP_FOR_EACH_34(x) x(35)
#define NEKO_PP_FOR_EACH_36(x) NEKO_PP_FOR_EACH_35(x) x(36)
#define NEKO_PP_FOR_EACH_37(x) NEKO_PP_FOR_EACH_36(x) x(37)
#define NEKO_PP_FOR_EACH_38(x) NEKO_PP_FOR_EACH_37(x) x(38)
#define NEKO_PP_FOR_EACH_39(x) NEKO_PP_FOR_EACH_38(x) x(39)
#define NEKO_PP_FOR_EACH_40(x) NEKO_PP_FOR_EACH_39(x) x(40)
#define NEKO_PP_FOR_EACH_41(x) NEKO_PP_FOR_EACH_40(x) x(41)
#define NEKO_PP_FOR_EACH_42(x) NEKO_PP_FOR_EACH_41(x) x(42)
#define NEKO_PP_FOR_EACH_43(x) NEKO_PP_FOR_EACH_42(x) x(43)
#define NEKO_PP_FOR_EACH_44(x) NEKO_PP_FOR_EACH_43(x) x(44)
#define NEKO_PP_FOR_EACH_45(x) NEKO_PP_FOR_EACH_44(x) x(45)
#define NEKO_PP_FOR_EACH_46(x) NEKO_PP_FOR_EACH_45(x) x(46)
#define NEKO_PP_FOR_EACH_47(x) NEKO_PP_FOR_EACH_46(x) x(47)
#define NEKO_PP_FOR_EACH_48(x) NEKO_PP_FOR_EACH_47(x) x(48)
#define NEKO_PP_FOR_EACH_49(x) NEKO_PP_FOR_EACH_48(x) x(49)
#define NEKO_PP_FOR_EACH_50(x) NEKO_PP_FOR_EACH_49(x) x(50)
#define NEKO_PP_FOR_EACH_51(x) NEKO_PP_FOR_EACH_50(x) x(51)
#define NEKO_PP_FOR_EACH_52(x) NEKO_PP_FOR_EACH_51(x) x(52)
#define NEKO_PP_FOR_EACH_53(x) NEKO_PP_FOR_EACH_52(x) x(53)
#define NEKO_PP_FOR_EACH_54(x) NEKO_PP_FOR_EACH_53(x) x(54)
#define NEKO_PP_FOR_EACH_55(x) NEKO_PP_FOR_EACH_54(x) x(55)
#define NEKO_PP_FOR_EACH_56(x) NEKO_PP_FOR_EACH_55(x) x(56)
#define NEKO_PP_FOR_EACH_57(x) NEKO_PP_FOR_EACH_56(x) x(57)
#define NEKO_PP_FOR_EACH_58(x) NEKO_PP_FOR_EACH_57(x) x(58)
#define NEKO_PP_FOR_EACH_59(x) NEKO_PP_FOR_EACH_58(x) x(59)
#define NEKO_PP_FOR_EACH_60(x) NEKO_PP_FOR_EACH_59(x) x(60)
#define NEKO_PP_FOR_EACH_61(x) NEKO_PP_FOR_EACH_60(x) x(61)
#define NEKO_PP_FOR_EACH_62(x) NEKO_PP_FOR_EACH_61(x) x(62)
#define NEKO_PP_FOR_EACH_63(x) NEKO_PP_FOR_EACH_62(x) x(63)

#define NEKO_PP_FOR_EACH(x, N) NEKO_PP_FOR_EACH_##N(x)

#endif
